version: "3.3"

services:
  database:
    container_name: "mysql-security"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_security
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3336:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    container_name: "backend"
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  db_data:
    driver: local
